notas/applications/nota/urls.py
#
from django.urls import path

from . import views

app_name = "nota_app"

urlpatterns = [
    path(
        '', 
        views.IndexView.as_view(),
        name='index',
    ),
    path(
        'lista-notas', 
        views.NotasListView.as_view(),
        name='lista',
    ),
    path(
        'add-notas', 
        views.NotaCreateView.as_view(),
        name='add',
    ),
    path(
        'detail-notas/<pk>/', 
        views.NotaDetailView.as_view(),
        name='detail',
    ),
]

notas/applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
]

notas/notas/urls.py
"""
proyecto ejemplo neunapp - django permissions
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.users.urls')),
    path('', include('applications.nota.urls')),
]

notas/applications/nota/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Nota(models.Model):

    title = models.CharField(
      'titulo', 
      max_length=30
    )
    description = models.TextField('descripcion')
    user_created = models.ForeignKey(
      settings.AUTH_USER_MODEL,
      on_delete=models.CASCADE,
    )

    class Meta:
      verbose_name = 'Nota'
      verbose_name_plural = 'Notas'
      # aqui debemos indicar permisos que si existan
      #permissions = [('can_view_nota', 'can view nota')]

    def __str__(self):
        return self.title

notas/applications/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
#
from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):

    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otros'),
    )

    email = models.EmailField(unique=True)
    full_name = models.CharField('Nombres', max_length=100)
    genero = models.CharField(
        max_length=1, 
        choices=GENDER_CHOICES, 
        blank=True
    )
    date_birth = models.DateField(
        'Fecha de nacimiento', 
        blank=True,
        null=True
    )
    #
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['full_name']

    objects = UserManager()

    def get_short_name(self):
        return self.email
    
    def get_full_name(self):
        return self.full_name

notas/applications/users/forms.py
  
from django import forms
from django.contrib.auth import authenticate
#
from .models import User

class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repetir Contraseña'
            }
        )
    )

    class Meta:

        model = User
        fields = (
            'email',
            'full_name',
            'genero',
            'date_birth',
        )
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Correo Electronico ...',
                }
            ),
            'full_name': forms.TextInput(
                attrs={
                    'placeholder': 'nombres ...',
                }
            ),
            'date_birth': forms.DateInput(
                attrs={
                    'type': 'date',
                },
            ),
        }
    
    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'Las contraseñas no son iguales')


class LoginForm(forms.Form):
    email = forms.CharField(
        label='E-mail',
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Correo Electronico',
            }
        )
    )
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'contraseña'
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        if not authenticate(email=email, password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos')
        
        return self.cleaned_data

notas/applications/nota/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    CreateView,
    DetailView
)
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseForbidden

#
from .models import Nota

class IndexView(TemplateView):
    template_name = "nota/index.html"


class NotasListView(PermissionRequiredMixin, ListView):
    model = Nota
    context_object_name = 'notas'
    template_name = "nota/lista.html"
    permission_required = 'nota.view_nota'
    permission_denied_message = 'no estas autorizado'


class NotaCreateView(CreateView):
    model = Nota
    fields = ('__all__')
    template_name = "nota/add.html"
    success_url = reverse_lazy('nota_app:lista')


class NotaDetailView(DetailView):
    model = Nota
    template_name = "nota/detail.html"

    def get(self, request, **kwargs):
        # verificamos permisos
        if not self.request.user.has_perm('nota.view_nota') :
            return HttpResponseForbidden()
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


notas/applications/users/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from django.views.generic import (
    View,
    CreateView
)

# for add permissions
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

from django.views.generic.edit import (
    FormView
)

#local apps
from applications.nota.models import Nota

from .forms import (
    UserRegisterForm, 
    LoginForm,
)
#
from .models import User
# 

class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        #
        usuario = User.objects.create_user(
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            full_name=form.cleaned_data['full_name'],
            genero=form.cleaned_data['genero'],
            date_birth=form.cleaned_data['date_birth'],
        )
        #recuperar el permiso
        content_type = ContentType.objects.get_for_model(Nota)
        permission = Permission.objects.get(
            codename='view_nota',
            content_type=content_type
        )
        usuario.user_permissions.add(permission)
        # enviar el codigo al email del user
        return super(UserRegisterView, self).form_valid(form)



class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('nota_app:index')

    def form_valid(self, form):
        user = authenticate(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):

    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )

notas/templates/nota/add.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Registrar Nota</title>
</head>
<body>
  <h3>Registrar Nota</h3>
  <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                            
    <div>
        <label>Titulo:
        {{ form.title }}
        </label>
    </div>
    <div>
        <label>Descripcion:
            {{ form.description }}
        </label>
    </div>
    <div>
      <label>Descripcion:
          {{ form.user_created }}
      </label>
    </div>
    <div>
        {% for error in  form.errors %}
          <p style="color:red;">{{ error }}</p>
        {% endfor %}
    </div>
    <p></p>
    <button type="submit">Registrar</button>
    <p></p>
    <a href="{% url 'nota_app:lista' %}" style="font-size: 20px;">Volver a Lista</a>
  </form>
</body>
</html>

notas/templates/nota/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Detalle Nota</title>
</head>
<body>
  <h3>{{ object.title }}</h3>
  <p></p>
  <p style="padding: 1em; background: aquamarine;">{{ object.description }}</p>

  <a href="{% url 'nota_app:lista' %}" style="font-size: 20px;">Volver a Lista</a>
</body>
</html>

notas/templates/nota/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Inicio</title>
</head>
<body>
  
  <h1>Inicio proyecto: ejemplo permission Django</h1>
  
  {% if user.is_active %}
    <h4>
      <span> Hola: {{ user.email }}  {{ user.full_name }} </span> <a href="{% url 'users_app:user-logout' %}">---->Salir</a>
    </h4>
  {% endif %}
    
  <ul>
    <li>
      <a href="{% url 'nota_app:lista' %}">Lista de Notas</a>
    </li>
    <li>
      <a href="{% url 'users_app:user-login' %}">Acceso de usuario</a>
    </li>
    <li>
      <a href="{% url 'users_app:user-register' %}">Registrar usuario</a>
    </li>
  </ul>
</body>
</html>

notas/templates/nota/lista.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lista notas</title>
</head>
<body>
  <h3>Lista de Notas Registradas</h3>
  <table border="1">
    <head>
      <th>ID</th>
      <th>titulo</th>
      <th>descripcion</th>
      <th>Accciones</th>
    </head>
    <tbody>
      
      {% for nota in notas  %}
        <tr>
          <td>
            {{ nota.id }}
          </td>
          <td>
            {{ nota.title }}
          </td>
          <td>
            {{ nota.description }}
          </td>
          <td>
            <a href="{% url 'nota_app:detail' nota.id %}">Ver Nota</a>
          </td>
        </tr>
      {% endfor %}
        
    </tbody>
  </table>
  <p></p>
  <a href="{% url 'nota_app:add' %}" style="font-size: 20px;">Registrar Nueva Nota</a>
  <p></p>
  <a href="{% url 'nota_app:index' %}" style="font-size: 20px;">Volver a Inicio</a>
</body>
</html>

notas/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
</head>
<body>
  <div style="margin-top: 2em;">
    <div>
        <div>
          <h4>Acceso de usuario</h4>
        </div>
        <div>
            <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div">
                    <label>Email:
                    {{form.email}}
                    </label>
                </div>
                <div>
                    <label>Contraseña:
                    {{form.password}}
                    </label>
                </div>
                <button type="submit">Acceder</button>
                <a href="{% url 'users_app:user-register' %}">Registrar</a>
            </form>
        </div>
    </div>
  </div>
</body>
</html>

notas/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Registrar</title>
</head>
<body>
  <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                            
    <div>
        <label>Email:
        {{ form.email }}
        </label>
    </div>
    <div>
        <label>Nombres:
            {{ form.full_name }}
        </label>
    </div>
    <div>
        <label>Genero:
            {{ form.genero }}
        </label>
    </div>
    <div>
        <label>Fecha Nacimiento:
            {{ form.date_birth }}
        </label>
    </div>
    <div>
        <label>Contraseña:
            {{ form.password1 }}
        </label>
    </div>
    <div>
        <label>Repetir Contraseña:
            {{ form.password2 }}
        </label>
        {% for error in  form.password2.errors %}
          <p style="color:red;">{{ error }}</p>
        {% endfor %}
    </div>
    <button type="submit">Registrar</button>
  </form>
</body>
</html>